/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "https://ktarcapgygzzbkcxaosr.supabase.co"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0YXJjYXBneWd6emJrY3hhb3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4NTcyODMsImV4cCI6MjA4MjQzMzI4M30.yKD55umkEqwbHIQ52_tp-xK1GNWzP07HYSNUWi8eDd4"